# Generated by Django 4.2.29 on 2026-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(),
        ),
    ]
